export interface BirthdayPhoto { src: string; alt: string; caption: string; note: string }

// Personalize this file. Local paths point to files inside public/.
export const birthday = {
  fullName: 'Neyna Salma Shidqy',
  nickname: 'Neyna',
  siteTitle: 'Neyna Salma Shidqy’s Birthday',
  description: 'A birthday celebration for Neyna Salma Shidqy, made with love by Novanni Indi Pradana.',
  brand: 'Neyna’s Birthday',
  madeWithLove: 'made with love',
  forLabel: 'FOR',
  brandForLabel: 'FOR',
  navigation: { label: 'Explore your surprise', birthday: 'For you', gallery: 'Little things', letter: 'A letter', wish: 'A wish' },
  intro: {
    eyebrow: 'A SURPRISE FOR YOU',
    title: 'Happy Birthday,',
    titleAccent: 'Neyna ♡',
    message: 'A little surprise is waiting for you.\nWrapped with a whole lot of love.',
    giftTag: 'for you ♡',
    annotation: 'psst… this is for you!',
    open: 'Open your surprise',
    opening: 'Just a little moment…',
    opened: 'Your surprise is here ♡',
    continue: 'Discover your surprise',
    footnote: 'a little gift. a lot of love.',
  },
  hero: {
    eyebrow: 'TODAY IS ALL ABOUT YOU',
    title: 'Happy Birthday,',
    titleAccent: 'Neyna! ♡',
    message: 'Happy birthday, Neyna. May today wrap you in all the warmth you bring into the world. I hope you feel loved in every little moment, because you deserve nothing less.',
    note: 'Today, we celebrate you.',
    caption: 'the birthday girl ♡',
    portrait: { src: '/images/portrait.jpg', alt: 'Portrait in a floral dress against a blue backdrop' },
    next: 'There is more for you',
    annotation: 'my favorite kind of lovely',
  },
  gallery: {
    eyebrow: 'THE LITTLE THINGS', title: 'Little Things', titleAccent: 'About You',
    description: 'Little reminders of all the lovely things that make you, you.',
    hint: 'Tap a picture. There is a little note just for you.',
    openLabel: 'Enlarge photo',
    placeholderNote: '',
    photos: [
      { src: '/images/little-joys.jpg', alt: 'Four-photo collage with popcorn, glasses, and a playful animal hat', caption: 'your little joys', note: 'Popcorn in your hands, a playful hat, and all these little expressions. I love how even a simple outing with you can fill a whole collage with reasons to smile.' },
      { src: '/images/sunshine.jpg', alt: 'Four mirror selfies in a blue cardigan', caption: 'a little sunshine', note: 'Four little glimpses of you in blue. No grand occasion needed; sometimes a few mirror selfies are enough to make an ordinary day worth remembering.' },
      { src: '/images/simple-moments.jpg', alt: 'Four mirror selfies in a grey pullover with a shoulder bag', caption: 'soft, simple moments', note: 'A grey pullover, your shoulder bag, and a few pauses in front of the mirror. These everyday versions of you are just as lovely as the dressed-up ones.' },
      { src: '/images/quiet-dreams.jpg', alt: 'Four-photo costume collage with a blonde wig and a decorative hand mirror', caption: 'all your quiet dreams', note: 'A blonde wig, a little hand mirror, and a whole new look. I love seeing you have fun with the things you enjoy, in your own wonderfully creative way.' },
      { src: '/images/bloom.jpg', alt: 'Four-photo collage wearing glasses and a black lace head covering', caption: 'bloom in your own way', note: 'The glasses, the black lace, and those little poses; every frame has its own personality. Keep showing up as yourself, in every style that makes you happy.' },
      { src: '/images/beautiful-days.jpg', alt: 'Three photos together in rain jackets and motorcycle helmets', caption: 'beautiful days ahead', note: 'Helmets on, rain jackets zipped, and still making room for a photo together. These are the moments I want more of: a little imperfect, a little ordinary, and ours.' },
    ] satisfies BirthdayPhoto[],
  },
  lightbox: { title: 'A little note for you', close: 'Close photo', previous: 'Previous photo', next: 'Next photo', hint: 'Swipe to discover another little note', unavailable: 'This photo is not available yet' },
  letter: {
    eyebrow: 'A FEW WORDS, FROM THE HEART', title: 'A Letter', titleAccent: 'Just for You',
    description: 'A few words I wanted you to hear on your special day.',
    envelopeLabel: 'a letter for you', open: 'Open your letter', close: 'Tuck it away',
    salutation: 'My dearest Neyna,',
    paragraphs: [
      'Happy birthday, Neyna Salma Shidqy. Today, I want you to know how much there is to celebrate about you. Your presence matters, on this special day and on all the ordinary days in between.',
      'As a new year of your life begins, I wish you good health, a peaceful heart, and the courage to follow the things you dream of. May you find reasons to laugh a little louder, and people and places that make you feel truly at home.',
      'When the days feel heavy, please remember that you are allowed to rest. You do not have to be strong every moment or have everything figured out. You are worthy of love just as you are, in all the ways that make you wonderfully you.',
      'For today, let your worries wait. Enjoy the cake, the warm hugs, and every lovely wish that comes your way. I hope this birthday is the beginning of so many beautiful things for you. More than anything, I hope you feel how deeply you are loved.',
    ],
    closing: 'With all my love,', signature: 'Novanni Indi Pradana ♡',
  },
  wish: {
    eyebrow: 'ONE LAST LITTLE THING', title: 'Make a', titleAccent: 'Wish',
    description: 'Close your eyes for a moment. Hold a little wish in your heart.',
    hint: 'Ready? Now, blow out the candles.', blow: 'Blow out the candles',
    candleLabel: 'Blow out candle', extinguishedLabel: 'Candle blown out',
    remainingLabel: 'Candles still glowing',
    successTitle: 'May all your wishes come true. ♡',
    successMessage: 'May every lovely wish find its way to you. Happy birthday, Neyna. You are so very loved.',
    replay: 'Unwrap it all again', candleCount: 3,
  },
  cat: {
    label: 'Pet the birthday cat',
    hint: 'psst... a little friend wants to say hello',
    message: 'A little birthday meow, just for you. ♡',
  },
  surprise: {
    eyebrow: 'ONE MORE THING, MY LOVE',
    title: 'I’m so lucky to have you.',
    message: 'The candles may be out, but there is still a little more love waiting for you.',
    open: 'A secret, just for you', close: 'Keep it close',
    secretTitle: 'My favorite part is you.',
    secretMessage: 'The popcorn, the silly photos, the helmets and rain jackets. What makes these little moments special is sharing them with you. For your birthday, I wish you all the love you bring into my life. Here’s to more pictures, more laughter, and more ordinary days that become our favorite memories.',
    signature: 'With you, even rainy days are worth keeping. ♡',
    balloons: 'Release the balloons again ♡',
  },
  music: {
    enabled: true, provider: 'local' as 'spotify' | 'local', src: '/until i found you cover.mp3', volume: 0.35,
    autoPlayOnLoad: true, autoPlayOnOpen: true,
    play: 'Play music', pause: 'Pause music', label: 'A little melody for you',
    unavailable: 'The music is not available yet. Your surprise is still here to enjoy.',
    blocked: 'The music could not start. Tap again to give it another try.',
    autoplayHint: 'Tap anywhere to let the melody begin.',
    spotify: {
      trackId: '5VKIlkAW6JnyPBlSJN0UOQ', title: 'Until I Found You', artist: 'Stephen Sanchez',
      open: 'A song for you', close: 'Close music player',
      heading: 'A little soundtrack for you',
      hint: 'Tap play and stay a little while. Spotify may play a preview.',
      external: 'Listen on Spotify',
      fallback: 'If the player is unavailable, you can listen on Spotify.',
      frameTitle: 'Spotify player: Until I Found You by Stephen Sanchez',
    },
  },
  footer: { text: 'For you, Neyna. With all my heart.', signature: 'Made with love by Novanni Indi Pradana', backToTop: 'Back to the top' },
  accessibility: { skip: 'Skip to the surprise' },
}
